services:
  web:
    build: .
    ports:
      - "8080:8080"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./env-deploy/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"