server:
  tomcat:
    #    accept-count: 1
    max-connections: 3
    threads:
      max: 3
    mbeanregistry:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"